server:
  port: 8004
spring:
  application:
    name: cloud-payment-service-zk
  cloud:
    zookeeper:
      connect-string: 192.168.66.128:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:com/jzl/cloudTest/mapper/*.xml
  type-aliases-package: com.jzl.cloudTest.pojo

