server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment1
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
#          filters: #官方提供的一些拦截器，主要的拦截器配置还是自定义
#            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/discovery/**
        - id: payment2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates: #能自定义各种条件和前端请求匹配
            - Path=/payment/MyLB/**
      discovery:
        locator:
          enabled: true
#  cloud:
#    gateway:

#




eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka



