server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-consul
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}

